-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYwodtW2EpyhMURO5
usnhTaJCMIR2Nw9apjHA8dueZ+igCgYIKoZIzj0DAQehRANCAATDKvlhMofCcfyf
E+p/9bptrtDwIvKbV9qt7zHLxvJ9BtgKSjwZvSpzJf/TEYxZoetB8MBdSxp5sy3W
h3AO1aS+
-----END PRIVATE KEY-----